### PR TITLE
Added WebBrowser control for login 

### PR DESCRIPTION
**Pull request by ghost**
This change will launch the Kite Login page in a WebBrowser control and automatically get back the request_token after authentication.

### CODE REVIEW

**Comment by ghost** [comment]
Hi @apurvaChaudhari , could you please review and merge these changes with your branch?
Let me know if you have any questions or need any changes to this.
Thanks,
Ishwar.

**Comment by apurvaChaudhari** [comment]
k ,
will do it by today evening or tomarrow.
thanks

**Comment by apurvaChaudhari** [comment]
hi @ishwarm  ,
Thanks for your help , really appreciate it.
If u wanna get in touch kindly contact me on +917208150179

**Comment by ghost** [comment]
Sure, will get in touch...

**Pull request merged**
